export const selectors = {
    day:{
        name:"narozeni_den",
        className:"mr2p"
    },
    month:{
        name:"narozeni_mesic",
        className:"mr2p"
    },
    year:{
        name:"narozeni_rok",
        className:""
    },
    hour:{
        name:"narozeni_hodina",
        className:"mr2p"
    },
    minute:{
        name:"narozeni_minuta",
        className:"mr2p"
    },
    city:{
        name:".narozeni_city",
        id:"city"
    },
    button:{
        parent:{
            className:"tc"
        },
        className:".button.ruka",
        type:"submit",
        value:"Рассчитать »"
    },
    link:{
        className:".tenky.ruka"
    },
    coords:{
        lat:{
            l1:{
                name:"narozeni_sirka_stupne"
            },
            l2:{
                name:"narozeni_sirka_minuty"
            },
            s:{
                name:"narozeni_sirka_smer"
            }
        },
        lng:{
            lng1:{
                name:"narozeni_delka_stupne"
            },
            lng2:{
                name:"narozeni_delka_minuty"
            },           
            s:{
                name:"narozeni_delka_smer"
            }
        }
    },
    table:{
        form:{
            id:"#vypocty_id_nativ"
        }
    }
}